name: games-app
static_sites:
- name: frontend
  github:
    repo: druidsmickey/falcon
    branch: main
  build_command: npm install && npm run build:prod
  output_dir: dist/games
  index_document: index.html
  error_document: index.html
  
services:
- name: backend
  source_dir: backend
  github:
    repo: druidsmickey/falcon
    branch: main
  build_command: npm install
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"